$(document).ready(function(){
    $("#STKBRKSBTN").click(function(){
        $("#STKBRKSBTN").addClass('activebtn');
        $("#FIRMBTN").removeClass('activebtn');
        $("#RankingsPeopleTableFull").removeClass('hidden');
        $("#RankingsFirmTableFull").addClass('hidden');
    });
    $("#FIRMBTN").click(function(){  	
        $("#STKBRKSBTN").removeClass('activebtn');
        $("#FIRMBTN").addClass('activebtn');
        $("#RankingsPeopleTableFull").addClass('hidden');
        $("#RankingsFirmTableFull").removeClass('hidden');
});
});